### ISSUE TITLE
Instruções mais detalhadas

### ISSUE THREAD

**Issue by darmsDD** [projeto-de-algoritmos/Grafos1_Cities#1]
## Descrição
Se possível colocar os métodos de instalação do pip3 e da virtualenv.

**Comment by lucasdutraf** [comment]
[Pronto](https://github.com/projeto-de-algoritmos/Grafos1_Turista/blob/master/README.md#instala%C3%A7%C3%A3o-dos-recursos-necess%C3%A1rios). Obrigado pelo feedback.
